version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run DynaLite Server
          command: yarn dynalite
          background: true

      # run tests!
      - run:
          name: Testing
          command: |
            export DYNALITE=http://localhost:4567
            yarn test-ci

      - run:
          name: Kill DynaLite Server
          command: kill $(ps -ax | grep dynalite | grep -v grep | awk '{print $1}')

      - store_test_results:
          path: ~/repo/build/junit.xml
