version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  shellcheck: circleci/shellcheck@1.3.15
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - shellcheck/check

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Testing
          command: yarn test

      - codecov/upload:
          file: build/coverage/lcov.info

      - store_test_results:
          path: build/

      - store_artifacts:
          path: build/

      - run:
          name: Semantic Release
          command: |
            rm -rf ./.circleci
            rm -rf ./.tmp
            rm -rf ./.vscode
            rm -rf ./build
            rm -f ./.gitignore
            rm -f ./.nycrc.json
            yarn semantic-release
