version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run DynaLite Server
          command: |
            set +e
            set +o pipefail
            yarn dynalite || true
          background: true

      - run:
          name: Testing
          command: yarn test-ci
          environment:
            DYNALITE: http://localhost:4567

      - run:
          name: Kill DynaLite Server
          command: kill $(ps -ax | grep dynalite | grep -v grep | awk '{print $1}')

      - codecov/upload:
          file: build/coverage/lcov.info

      - store_test_results:
          path: build/

      - store_artifacts:
          path: build/

      - run:
          name: Semantic Release
          command: |
            rm -rf ./.circleci
            rm -rf ./.tmp
            rm -rf ./.vscode
            rm -rf ./build
            rm -f ./.gitignore
            rm -f ./.nycrc.json
            yarn semantic-release
